dbt_with_bq:
  outputs:
    dev:
      dataset: iykra_playgorund
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cedar-lexicon-379510
      threads: 1
      type: bigquery
  target: dev
